# Most of this is from https://github.com/PHPirates/travis-ci-latex-pdf under MIT License

notifications:
  email: false

install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda update --all;
      conda install tectonic;
    fi
  - conda info -a
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
script: # Change working directory each time so including files will work. Change back so the pdfs can be found for deployment. This way, building multiple files goes well.
  - cd ./src/
  - tectonic ./Resume_Alex-Aubuchon.tex
  - cd ../

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "A-lxe"
  - git config --local user.email "alex@alxe.me"
  - git tag "latest"
deploy:
  provider: releases
  api_key:
    secure: jExAjJ5rumsfKP9JfLWJP7Scz8rO85aK/7T1sT8JWlP7DKqcXLx/5UcL2vZ8UbK8EkqotOYJcgERFQAGnZ4Jhc1tYMskpHrAm22E0DDz22Z7jjvJYz8gI6iZPZzsP+NShZpckLpnUzIwasLWq9hSVLoCqPWOOUPs8s2Hbwcby/9h+7eGMih/OSExNF+54Dwny7FzPx4TP0KMGV2ByMN831AgEA9V9nHCOthUmVhTHuNL2d1nCmeXoO5m7ae/nC8oRLU9BFfnL115/WCDZ1yiBSdOLAinW0lDiUZKvcwnMWKYz/fLRi1KQhqZh6wsSQzA87PWHkna3WVNtwOZ8F6YDiLkEEhLNeTqLQvdXzT4mytjSWg5DAUKGGxRukE3kvT1EqhG8buY6jI38XwNsiHXt2OKx3q4L6qLpbSmxMrBfT1SqIzgFjFAH/Cccz/5DIkYt8spNVlm/rcl68qVEl54sfWxxnjtVk2yHwoWTZJXkQzv0qxWxCbQdiRvgqADxJvk95vCU66OfhgOSJIHrI3s18HfUSV8pvXEoWqV5NfIzIvtrN5tt5zSifhbX7+ID5EE0b4rrnvx7oOdemeQ8UsSfy5tPxNxFx6WoKUvHvfxzOGOouoBTaEkNEl66PGDAaGIvpB421TRm+d7Wujsp45nzmIr6w+PY1Ck/+MbNb5NHSo=
  file: ./src/Resume_Alex-Aubuchon.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: A-lxe/resume
    branch: master
